package mysticmods.roots.api.datamap;

import com.mojang.serialization.Codec;
import com.mojang.serialization.MapCodec;
import com.mojang.serialization.codecs.RecordCodecBuilder;
import io.netty.buffer.ByteBuf;
import net.minecraft.core.Holder;
import net.minecraft.core.registries.BuiltInRegistries;
import net.minecraft.network.codec.ByteBufCodecs;
import net.minecraft.network.codec.StreamCodec;
import net.minecraft.world.entity.ai.attributes.Attribute;

import java.util.Map;

// This is stored in a Map<Holder<Attribute>, AugmentationInfo>.
// Generated by member functions of AugmentationData.
public record AugmentationInfo(int smallCount, int largeCount) {
  public static final MapCodec<AugmentationInfo> MAP_CODEC = RecordCodecBuilder.mapCodec(instance -> instance.group(
          Codec.INT.fieldOf("small_count").forGetter(AugmentationInfo::smallCount),
          Codec.INT.fieldOf("large_count").forGetter(AugmentationInfo::largeCount))
      .apply(instance, AugmentationInfo::new));
  public static final Codec<AugmentationInfo> CODEC = MAP_CODEC.codec();
  public static final StreamCodec<ByteBuf, AugmentationInfo> STREAM_CODEC = StreamCodec.composite(
      ByteBufCodecs.VAR_INT, AugmentationInfo::smallCount,
      ByteBufCodecs.VAR_INT, AugmentationInfo::largeCount,
      AugmentationInfo::new);
  public static final Codec<Map<Holder<Attribute>, AugmentationInfo>> DATA_MAP_CODEC = Codec.unboundedMap(BuiltInRegistries.ATTRIBUTE.holderByNameCodec(), AugmentationInfo.CODEC);

  public static AugmentationInfo EMPTY = new AugmentationInfo(0, 0);

  public boolean isEmpty() {
    return (smallCount == 0 && largeCount == 0) || this == EMPTY;
  }
}
