# Sets default memory used for gradle commands. Can be overridden by user or command line properties.
org.gradle.jvmargs=-Xmx1G
org.gradle.daemon=true
org.gradle.parallel=true
org.gradle.caching=true
org.gradle.configuration-cache=true

parchment_minecraft_version=1.21.1
parchment_mappings_version=2024.11.17
minecraft_version=1.21.1
minecraft_version_range=[1.21.1, 1.22)
neo_version=21.1.192
neo_version_range=[21.1.0,)
loader_version_range=[2,)
jei_version=19.21.0.247
curios_version=9.2.2+1.21.1

mod_id=roots
mod_name=Roots
mod_license=MIT
mod_version=4.0.0.14-alpha
mod_group_id=mysticmods.roots
mod_authors=Noobanidus
mod_description=Natural magic.

mixin_extras=0.3.6

curse_project=246183
curse_page=https://www.curseforge.com/minecraft/mc-mods/roots
curse_release_type=alpha
curse_versions=1.21.1, NeoForge
curse_slug=roots
java_21=true

git_previous_commit=ac7df0cc3ee65dde3a9900f485a97e36db185df8
