# Sets default memory used for gradle commands. Can be overridden by user or command line properties.
org.gradle.jvmargs=-Xmx1G
org.gradle.daemon=true
org.gradle.parallel=true
org.gradle.caching=true
org.gradle.configuration-cache=true

parchment_minecraft_version=1.21.1
parchment_mappings_version=2024.11.17
minecraft_version=1.21.1
minecraft_version_range=[1.21.1, 1.22)
neo_version=21.1.93
neo_version_range=[21.1.0,)
loader_version_range=[4,)
jei_version=19.21.0.247
curios_version=9.2.2+1.21.1

mod_id=roots
mod_name=Roots
mod_license=MIT
mod_version=4.0.0.0
mod_group_id=mysticmods.roots
mod_authors=Noobanidus
mod_description=Natural magic.

mixin_extras=0.3.6
