# Sets default memory used for gradle commands. Can be overridden by user or command line properties.
# This is required to provide enough memory for the Minecraft decompilation process.
org.gradle.jvmargs=-Xmx6500M
org.gradle.daemon=false

group=mysticmods.roots
version=4.0.0

mod_name=Roots
mod_author=Noobanidus
mod_id=roots
mod_homepage=https://www.curseforge.com/minecraft/mc-mods/roots
mod_source=https://github.com/MysticMods/Roots
mod_issues=https://github.com/MysticMods/Roots/issues
mod_description=Magic with a natural flair!
mod_license=mit
mixin_id=roots

# ForgeGradle properties (gradle/forge.gradle)
minecraft_version=1.20.6
minecraft_version_range=[1.20.5,1.21)
neo_version=20.6.112-beta
neo_version_range=[20.6,)
loader_version_range=[2,)
#forge_version=20.4.114-beta
forge_at=src/main/resources/META-INF/accesstransformer.cfg

# CurseForge properties (gradle/curseforge.gradle)
curse_project=246183
curse_page=https://www.curseforge.com/minecraft/mc-mods/roots
curse_release_type=beta
curse_versions=1.20.4

# Are we running on Jenkins?
jenkins=true
java_21=true

remapRefmap=true
remapRefmapFile=${projectDir}/build/createSrgToMcp/output.srg

neogradle.subsystems.parchment.minecraftVersion=1.20.6
neogradle.subsystems.parchment.mappingsVersion=2024.05.01

git_previous_commit=b06155c3a16396cba99d1c1a270ce7207e181dfa