modLoader="javafml" 
loaderVersion="[43,)"
issueTrackerURL="https://github.com/MysticMods/Roots/issues"
license="https://github.com/MysticMods/Roots/blob/master/LICENSE"
[[mods]] 
modId="roots" 
version="${version}"
displayName="Roots"
displayURL="https://minecraft.curseforge.com/projects/roots"
credits="Elucent, EpicSquid, Martacus, Davoleo"
authors="Noobanidus"
description='''
A nature-themed magical mod!
'''
[[dependencies.roots]]
    modId="forge"
    mandatory=true
    versionRange="[43,)"
    ordering="NONE"
    side="BOTH"
[[dependencies.roots]]
    modId="minecraft"
    mandatory=true
    versionRange="[1.19.2,)"
    ordering="NONE"
    side="BOTH"