modLoader="javafml" 
loaderVersion="[2,)"
issueTrackerURL="https://github.com/mysticmods/Roots/issues"
license="https://github.com/mysticmods/roots/arch-1.21/LICENSE"
[[mods]]
    modId="roots"
    version="4.0.0.0"
    displayName="Roots"
    displayURL="https://minecraft.curseforge.com/projects/roots"
    authors="Noobanidus"
    description="Natural magic."

[[mixins]]
    config="roots-neoforge.mixins.json"

[[dependencies.roots]]
    modId="minecraft"
    type="required"
    versionRange="1.21.1"

 [[dependencies.roots]]
    modId="neoforge"
    type="required"
    versionRange="[21,)"
