package mysticmods.roots.init;

import mysticmods.roots.api.RootsAPI;
import mysticmods.roots.api.RootsTags;
import mysticmods.roots.block.*;
import mysticmods.roots.block.crop.ElementalCropBlock;
import mysticmods.roots.block.crop.ThreeStageCropBlock;
import mysticmods.roots.block.crop.WaterElementalCropBlock;
import mysticmods.roots.worldgen.trees.RootsTreeGrowers;
import net.minecraft.util.valueproviders.ConstantInt;
import net.minecraft.util.valueproviders.UniformInt;
import net.minecraft.world.level.block.*;
import net.minecraft.world.level.block.state.BlockBehaviour;
import net.neoforged.bus.api.IEventBus;
import net.neoforged.neoforge.registries.DeferredHolder;
import net.neoforged.neoforge.registries.DeferredRegister;

public class ModBlocks {
  private static final DeferredRegister.Blocks BLOCKS = DeferredRegister.createBlocks(RootsAPI.MODID);

  private static final BlockBehaviour.Properties RUNESTONE_PROPERTIES = BlockBehaviour.Properties.ofFullCopy(Blocks.STONE);
  private static final BlockBehaviour.Properties RUNED_PROPERTIES = BlockBehaviour.Properties.ofFullCopy(Blocks.OBSIDIAN);
  private static final BlockBehaviour.Properties ORE_PROPERTIES = BlockBehaviour.Properties.ofFullCopy(Blocks.IRON_ORE);
  private static final BlockBehaviour.Properties DEEPSLATE_ORE_PROPERTIES = BlockBehaviour.Properties.ofFullCopy(Blocks.DEEPSLATE_IRON_ORE);
  // TODO: Colour?
  private static final BlockBehaviour.Properties RAW_BLOCK = BlockBehaviour.Properties.ofFullCopy(Blocks.RAW_IRON_BLOCK);
  private static final BlockBehaviour.Properties WILDWOOD_LOG_PROPERTIES = BlockBehaviour.Properties.ofFullCopy(net.minecraft.world.level.block.Blocks.OAK_LOG);
  public static final BlockBehaviour.Properties WILDWOOD_PLANKS_PROPERTIES = BlockBehaviour.Properties.ofFullCopy(net.minecraft.world.level.block.Blocks.OAK_PLANKS);
  public static BlockBehaviour.Properties WILDWOOD_LEAVES_PROPERTIES = BlockBehaviour.Properties.ofFullCopy(net.minecraft.world.level.block.Blocks.OAK_LEAVES);
  private static final BlockBehaviour.Properties RUNED_LOG_PROPERTIES = BlockBehaviour.Properties.ofFullCopy(net.minecraft.world.level.block.Blocks.OAK_LOG);
  private static final BlockBehaviour.Properties RUNED_STEM_PROPERTIES = BlockBehaviour.Properties.ofFullCopy(net.minecraft.world.level.block.Blocks.CRIMSON_STEM);
  private static final BlockBehaviour.Properties RUNESTONE_BUTTON_PROPERTIES = BlockBehaviour.Properties.ofFullCopy(net.minecraft.world.level.block.Blocks.STONE_BUTTON);
  public static BlockBehaviour.Properties SOIL_PROPERTIES = BlockBehaviour.Properties.ofFullCopy(net.minecraft.world.level.block.Blocks.DIRT);
  public static final BlockBehaviour.Properties BASE_PROPERTIES = BlockBehaviour.Properties.of().dynamicShape().noOcclusion().strength(1.5f).sound(SoundType.STONE);
  public static final BlockBehaviour.Properties BASE_WOODEN_PROPERTIES = BlockBehaviour.Properties.of().dynamicShape().noOcclusion().strength(1.5f).sound(SoundType.WOOD);
  public static final BlockBehaviour.Properties BASE_REINFORCED_PROPERTIES = BlockBehaviour.Properties.of().dynamicShape().noOcclusion().strength(1.5f).sound(SoundType.STONE).requiresCorrectToolForDrops().strength(50.0F, 1200.0F);
  public static BlockBehaviour.Properties CROP_PROPERTIES = BlockBehaviour.Properties.ofFullCopy(Blocks.WHEAT);

  public static DeferredHolder<Block, WaterloggedBlock> THATCH = BLOCKS.register("thatch", () -> new WaterloggedBlock(BlockBehaviour.Properties.ofFullCopy(Blocks.HAY_BLOCK)));
  public static DeferredHolder<Block, Block> RUNESTONE = BLOCKS.register("runestone", () -> new Block(RUNESTONE_PROPERTIES));
  public static DeferredHolder<Block, Block> MOSSY_RUNESTONE = BLOCKS.register("mossy_runestone", () -> new Block(RUNESTONE_PROPERTIES));
  public static DeferredHolder<Block, Block> CHISELED_RUNESTONE = BLOCKS.register("chiseled_runestone", () -> new Block(RUNESTONE_PROPERTIES));
  public static DeferredHolder<Block, Block> RUNESTONE_BRICK = BLOCKS.register("runestone_brick", () -> new Block(RUNESTONE_PROPERTIES));
  public static DeferredHolder<Block, Block> RUNESTONE_TILE = BLOCKS.register("runestone_tile", () -> new Block(RUNESTONE_PROPERTIES));
  public static DeferredHolder<Block, Block> RUNED_OBSIDIAN = BLOCKS.register("runed_obsidian", () -> new Block(RUNED_PROPERTIES));
  public static DeferredHolder<Block, Block> CHISELED_RUNED_OBSIDIAN = BLOCKS.register("chiseled_runed_obsidian", () -> new Block(RUNED_PROPERTIES));
  public static DeferredHolder<Block, Block> RUNED_BRICK = BLOCKS.register("runed_brick", () -> new Block(RUNED_PROPERTIES));
  public static DeferredHolder<Block, Block> RUNED_TILE = BLOCKS.register("runed_tile", () -> new Block(RUNED_PROPERTIES));
  // TODO: Fix the experience
  public static DeferredHolder<Block, DropExperienceBlock> SILVER_ORE = BLOCKS.register("silver_ore", () -> new DropExperienceBlock(ConstantInt.of(0), ORE_PROPERTIES));
  public static DeferredHolder<Block, DropExperienceBlock> DEEPSLATE_SILVER_ORE = BLOCKS.register("deepslate_silver_ore", () -> new DropExperienceBlock(ConstantInt.of(0), DEEPSLATE_ORE_PROPERTIES));
  public static DeferredHolder<Block, DropExperienceBlock> GRANITE_QUARTZ_ORE = BLOCKS.register("granite_quartz_ore", () -> new DropExperienceBlock(UniformInt.of(2, 5), ORE_PROPERTIES));
  public static DeferredHolder<Block, Block> RAW_SILVER_BLOCK = BLOCKS.register("raw_silver_block", () -> new Block(RAW_BLOCK));
  public static DeferredHolder<Block, Block> SILVER_BLOCK = BLOCKS.register("silver_block", () -> new Block(BlockBehaviour.Properties.ofFullCopy(Blocks.IRON_BLOCK)));
  public static DeferredHolder<Block, RotatedPillarBlock> WILDWOOD_LOG = BLOCKS.register("wildwood_log", () -> new RotatedPillarBlock(WILDWOOD_LOG_PROPERTIES));
  public static DeferredHolder<Block, RotatedPillarBlock> STRIPPED_WILDWOOD_LOG = BLOCKS.register("stripped_wildwood_log", () -> new RotatedPillarBlock(WILDWOOD_LOG_PROPERTIES));
  public static DeferredHolder<Block, RotatedPillarBlock> WILDWOOD_WOOD = BLOCKS.register("wildwood_wood", () -> new RotatedPillarBlock(WILDWOOD_LOG_PROPERTIES));
  public static DeferredHolder<Block, RotatedPillarBlock> STRIPPED_WILDWOOD_WOOD = BLOCKS.register("stripped_wildwood_wood", () -> new RotatedPillarBlock(WILDWOOD_LOG_PROPERTIES));
  public static DeferredHolder<Block, Block> WILDWOOD_PLANKS = BLOCKS.register("wildwood_planks", () -> new Block(WILDWOOD_PLANKS_PROPERTIES));
  public static DeferredHolder<Block, SaplingBlock> WILDWOOD_SAPLING = BLOCKS.register("wildwood_sapling", () -> new SaplingBlock(RootsTreeGrowers.WILDWOOD_TREE, BlockBehaviour.Properties.ofFullCopy(Blocks.OAK_SAPLING)));

  // TODO: Whatever happened to plant types?
  public static DeferredHolder<Block, PetrifiedFlowerBlock> STONEPETAL = BLOCKS.register("stonepetal", () -> new PetrifiedFlowerBlock(BlockBehaviour.Properties.of().noCollission().instabreak().sound(SoundType.GRASS).noOcclusion()));
  public static DeferredHolder<Block, LeavesBlock> WILDWOOD_LEAVES = BLOCKS.register("wildwood_leaves", () -> new LeavesBlock(WILDWOOD_LEAVES_PROPERTIES));
  public static DeferredHolder<Block, RotatedPillarBlock> RUNED_WILDWOOD_LOG = BLOCKS.register("runed_wildwood_log", () -> new RotatedPillarBlock(RUNED_LOG_PROPERTIES));
  public static DeferredHolder<Block, RotatedPillarBlock> RUNED_SPRUCE_LOG = BLOCKS.register("runed_spruce_log", () -> new RotatedPillarBlock(RUNED_LOG_PROPERTIES));
  public static DeferredHolder<Block, RotatedPillarBlock> RUNED_JUNGLE_LOG = BLOCKS.register("runed_jungle_log", () -> new RotatedPillarBlock(RUNED_LOG_PROPERTIES));
  public static DeferredHolder<Block, RotatedPillarBlock> RUNED_BIRCH_LOG = BLOCKS.register("runed_birch_log", () -> new RotatedPillarBlock(RUNED_LOG_PROPERTIES));
  public static DeferredHolder<Block, RotatedPillarBlock> RUNED_OAK_LOG = BLOCKS.register("runed_oak_log", () -> new RotatedPillarBlock(RUNED_LOG_PROPERTIES));
  public static DeferredHolder<Block, RotatedPillarBlock> RUNED_DARK_OAK_LOG = BLOCKS.register("runed_dark_oak_log", () -> new RotatedPillarBlock(RUNED_LOG_PROPERTIES));
  public static DeferredHolder<Block, RotatedPillarBlock> RUNED_ACACIA_LOG = BLOCKS.register("runed_acacia_log", () -> new RotatedPillarBlock(RUNED_LOG_PROPERTIES));
  public static DeferredHolder<Block, RotatedPillarBlock> RUNED_MANGROVE_LOG = BLOCKS.register("runed_mangrove_log", () -> new RotatedPillarBlock(RUNED_LOG_PROPERTIES));
  public static DeferredHolder<Block, RotatedPillarBlock> RUNED_WARPED_STEM = BLOCKS.register("runed_warped_stem", () -> new RotatedPillarBlock(RUNED_STEM_PROPERTIES));
  public static DeferredHolder<Block, RotatedPillarBlock> RUNED_CRIMSON_STEM = BLOCKS.register("runed_crimson_stem", () -> new RotatedPillarBlock(RUNED_STEM_PROPERTIES));
  public static DeferredHolder<Block, StairBlock> RUNESTONE_STAIRS = BLOCKS.register("runestone_stairs", () -> new StairBlock(ModBlocks.RUNESTONE.get().defaultBlockState(), RUNESTONE_PROPERTIES));
  public static DeferredHolder<Block, StairBlock> MOSSY_RUNESTONE_STAIRS = BLOCKS.register("mossy_runestone_stairs", () -> new StairBlock(ModBlocks.MOSSY_RUNESTONE.get().defaultBlockState(), RUNESTONE_PROPERTIES));
  public static DeferredHolder<Block, StairBlock> RUNESTONE_BRICK_STAIRS = BLOCKS.register("runestone_brick_stairs", () -> new StairBlock(ModBlocks.RUNESTONE_BRICK.get().defaultBlockState(), RUNESTONE_PROPERTIES));
  public static DeferredHolder<Block, StairBlock> RUNESTONE_TILE_STAIRS = BLOCKS.register("runestone_tile_stairs", () -> new StairBlock(ModBlocks.RUNESTONE_TILE.get().defaultBlockState(), RUNESTONE_PROPERTIES));
  public static DeferredHolder<Block, RunedObsidianBlocks.Stairs> RUNED_STAIRS = BLOCKS.register("runed_stairs", () -> new RunedObsidianBlocks.Stairs(RUNED_PROPERTIES));
  public static DeferredHolder<Block, RunedObsidianBlocks.Stairs> RUNED_BRICK_STAIRS = BLOCKS.register("runed_brick_stairs", () -> new RunedObsidianBlocks.Stairs(RUNED_PROPERTIES));
  public static DeferredHolder<Block, RunedObsidianBlocks.Stairs> RUNED_TILE_STAIRS = BLOCKS.register("runed_tile_stairs", () -> new RunedObsidianBlocks.Stairs(RUNED_PROPERTIES));
  public static DeferredHolder<Block, StairBlock> WILDWOOD_STAIRS = BLOCKS.register("wildwood_stairs", () -> new StairBlock(ModBlocks.WILDWOOD_PLANKS.get().defaultBlockState(), WILDWOOD_PLANKS_PROPERTIES));
  public static DeferredHolder<Block, SlabBlock> RUNESTONE_SLAB = BLOCKS.register("runestone_slab", () -> new SlabBlock(RUNESTONE_PROPERTIES));
  public static DeferredHolder<Block, SlabBlock> MOSSY_RUNESTONE_SLAB = BLOCKS.register("mossy_runestone_slab", () -> new SlabBlock(RUNESTONE_PROPERTIES));
  public static DeferredHolder<Block, SlabBlock> RUNESTONE_BRICK_SLAB = BLOCKS.register("runestone_brick_slab", () -> new SlabBlock(RUNESTONE_PROPERTIES));
  public static DeferredHolder<Block, SlabBlock> RUNESTONE_TILE_SLAB = BLOCKS.register("runestone_tile_slab", () -> new SlabBlock(RUNESTONE_PROPERTIES));
  public static DeferredHolder<Block, RunedObsidianBlocks.Slab> RUNED_SLAB = BLOCKS.register("runed_slab", () -> new RunedObsidianBlocks.Slab(RUNED_PROPERTIES));
  public static DeferredHolder<Block, RunedObsidianBlocks.Slab> RUNED_BRICK_SLAB = BLOCKS.register("runed_brick_slab", () -> new RunedObsidianBlocks.Slab(RUNED_PROPERTIES));
  public static DeferredHolder<Block, RunedObsidianBlocks.Slab> RUNED_TILE_SLAB = BLOCKS.register("runed_tile_slab", () -> new RunedObsidianBlocks.Slab(RUNED_PROPERTIES));
  public static DeferredHolder<Block, SlabBlock> WILDWOOD_SLAB = BLOCKS.register("wildwood_slab", () -> new SlabBlock(WILDWOOD_PLANKS_PROPERTIES));
  public static DeferredHolder<Block, FenceBlock> WILDWOOD_FENCE = BLOCKS.register("wildwood_fence", () -> new FenceBlock(WILDWOOD_PLANKS_PROPERTIES));
  public static DeferredHolder<Block, ButtonBlock> RUNESTONE_BUTTON = BLOCKS.register("runestone_button", () -> new ButtonBlock(ModTypes.RUNESTONE_SET, 20, RUNESTONE_BUTTON_PROPERTIES));
  public static DeferredHolder<Block, ButtonBlock> RUNESTONE_BRICK_BUTTON = BLOCKS.register("runestone_brick_button", () -> new ButtonBlock(ModTypes.RUNESTONE_SET, 20, RUNESTONE_BUTTON_PROPERTIES));
  public static DeferredHolder<Block, ButtonBlock> RUNESTONE_TILE_BUTTON = BLOCKS.register("runestone_tile_button", () -> new ButtonBlock(ModTypes.RUNESTONE_SET, 20, RUNESTONE_BUTTON_PROPERTIES));
  public static DeferredHolder<Block, ButtonBlock> MOSSY_RUNESTONE_BUTTON = BLOCKS.register("mossy_runestone_button", () -> new ButtonBlock(ModTypes.RUNESTONE_SET, 20, RUNESTONE_BUTTON_PROPERTIES));
  public static DeferredHolder<Block, RunedObsidianBlocks.Button> RUNED_BUTTON = BLOCKS.register("runed_button", () -> new RunedObsidianBlocks.Button(ModTypes.RUNED_OBSIDIAN_SET, 20, RUNESTONE_BUTTON_PROPERTIES));
  public static DeferredHolder<Block, RunedObsidianBlocks.Button> RUNED_BRICK_BUTTON = BLOCKS.register("runed_brick_button", () -> new RunedObsidianBlocks.Button(ModTypes.RUNED_OBSIDIAN_SET, 20, RUNESTONE_BUTTON_PROPERTIES));
  public static DeferredHolder<Block, RunedObsidianBlocks.Button> RUNED_TILE_BUTTON = BLOCKS.register("runed_tile_button", () -> new RunedObsidianBlocks.Button(ModTypes.RUNED_OBSIDIAN_SET, 20, RUNESTONE_BUTTON_PROPERTIES));
  public static DeferredHolder<Block, ButtonBlock> WILDWOOD_BUTTON = BLOCKS.register("wildwood_button", () -> new ButtonBlock(ModTypes.WILDWOOD_SET, 20, WILDWOOD_PLANKS_PROPERTIES));
  public static DeferredHolder<Block, PressurePlateBlock> RUNESTONE_PRESSURE_PLATE = BLOCKS.register("runestone_pressure_plate", () -> new PressurePlateBlock(ModTypes.RUNESTONE_SET, RUNESTONE_PROPERTIES));
  public static DeferredHolder<Block, PressurePlateBlock> RUNESTONE_BRICK_PRESSURE_PLATE = BLOCKS.register("runestone_brick_pressure_plate", () -> new PressurePlateBlock(ModTypes.RUNESTONE_SET, RUNESTONE_PROPERTIES));
  public static DeferredHolder<Block, PressurePlateBlock> RUNESTONE_TILE_PRESSURE_PLATE = BLOCKS.register("runestone_tile_pressure_plate", () -> new PressurePlateBlock(ModTypes.RUNESTONE_SET, RUNESTONE_PROPERTIES));
  public static DeferredHolder<Block, PressurePlateBlock> MOSSY_RUNESTONE_PRESSURE_PLATE = BLOCKS.register("mossy_runestone_pressure_plate", () -> new PressurePlateBlock(ModTypes.RUNESTONE_SET, RUNESTONE_PROPERTIES));
  public static DeferredHolder<Block, RunedObsidianBlocks.PressurePlate> RUNED_PRESSURE_PLATE = BLOCKS.register("runed_pressure_plate", () -> new RunedObsidianBlocks.PressurePlate(ModTypes.RUNED_OBSIDIAN_SET, RUNED_PROPERTIES));
  public static DeferredHolder<Block, RunedObsidianBlocks.PressurePlate> RUNED_BRICK_PRESSURE_PLATE = BLOCKS.register("runed_brick_pressure_plate", () -> new RunedObsidianBlocks.PressurePlate(ModTypes.RUNED_OBSIDIAN_SET, RUNED_PROPERTIES));
  public static DeferredHolder<Block, RunedObsidianBlocks.PressurePlate> RUNED_TILE_PRESSURE_PLATE = BLOCKS.register("runed_tile_pressure_plate", () -> new RunedObsidianBlocks.PressurePlate(ModTypes.RUNED_OBSIDIAN_SET, RUNED_PROPERTIES));
  public static DeferredHolder<Block, PressurePlateBlock> WILDWOOD_PRESSURE_PLATE = BLOCKS.register("wildwood_pressure_plate", () -> new PressurePlateBlock(ModTypes.WILDWOOD_SET, WILDWOOD_PLANKS_PROPERTIES));
  public static DeferredHolder<Block, DoorBlock> WILDWOOD_DOOR = BLOCKS.register("wildwood_door", () -> new DoorBlock(ModTypes.WILDWOOD_SET, WILDWOOD_PLANKS_PROPERTIES));
  public static DeferredHolder<Block, TrapDoorBlock> WILDWOOD_TRAPDOOR = BLOCKS.register("wildwood_trapdoor", () -> new TrapDoorBlock(ModTypes.WILDWOOD_SET, WILDWOOD_PLANKS_PROPERTIES));
  public static DeferredHolder<Block, LadderBlock> WILDWOOD_LADDER = BLOCKS.register("wildwood_ladder", () -> new LadderBlock(BlockBehaviour.Properties.ofFullCopy(Blocks.LADDER)));
  public static DeferredHolder<Block, FenceGateBlock> WILDWOOD_GATE = BLOCKS.register("wildwood_gate", () -> new FenceGateBlock(ModTypes.WILDWOOD_WOOD_TYPE, WILDWOOD_PLANKS_PROPERTIES));
  public static DeferredHolder<Block, WallBlock> RUNESTONE_WALL = BLOCKS.register("runestone_wall", () -> new WallBlock(RUNESTONE_PROPERTIES));
  public static DeferredHolder<Block, WallBlock> MOSSY_RUNESTONE_WALL = BLOCKS.register("mossy_runestone_wall", () -> new WallBlock(RUNESTONE_PROPERTIES));
  public static DeferredHolder<Block, WallBlock> RUNESTONE_BRICK_WALL = BLOCKS.register("runestone_brick_wall", () -> new WallBlock(RUNESTONE_PROPERTIES));
  public static DeferredHolder<Block, WallBlock> RUNESTONE_TILE_WALL = BLOCKS.register("runestone_tile_wall", () -> new WallBlock(RUNESTONE_PROPERTIES));
  public static DeferredHolder<Block, RunedObsidianBlocks.Wall> RUNED_WALL = BLOCKS.register("runed_wall", () -> new RunedObsidianBlocks.Wall(RUNED_PROPERTIES));
  public static DeferredHolder<Block, RunedObsidianBlocks.Wall> RUNED_BRICK_WALL = BLOCKS.register("runed_brick_wall", () -> new RunedObsidianBlocks.Wall(RUNED_PROPERTIES));
  public static DeferredHolder<Block, RunedObsidianBlocks.Wall> RUNED_TILE_WALL = BLOCKS.register("runed_tile_wall", () -> new RunedObsidianBlocks.Wall(RUNED_PROPERTIES));
  public static DeferredHolder<Block, ElementalSoilBlock> ELEMENTAL_SOIL = BLOCKS.register("elemental_soil", () -> new ElementalSoilBlock(SOIL_PROPERTIES));
  public static DeferredHolder<Block, ElementalSoilBlock> AQUEOUS_SOIL = BLOCKS.register("aqueous_soil", () -> new ElementalSoilBlock(SOIL_PROPERTIES));
  public static DeferredHolder<Block, ElementalSoilBlock> CAELIC_SOIL = BLOCKS.register("caelic_soil", () -> new ElementalSoilBlock(SOIL_PROPERTIES));
  public static DeferredHolder<Block, ElementalSoilBlock> MAGMATIC_SOIL = BLOCKS.register("magmatic_soil", () -> new ElementalSoilBlock(SOIL_PROPERTIES));
  public static DeferredHolder<Block, ElementalSoilBlock> TERRAN_SOIL = BLOCKS.register("terran_soil", () -> new ElementalSoilBlock(SOIL_PROPERTIES));
  // TODO all: voxel shapes & bounding boxes
  public static DeferredHolder<Block, FeyLightBlock> FEY_LIGHT = BLOCKS.register("fey_light", () -> new FeyLightBlock(BASE_PROPERTIES));
  public static DeferredHolder<Block, RitualPedestalBlock> RITUAL_PEDESTAL = BLOCKS.register("ritual_pedestal", () -> new RitualPedestalBlock(BASE_PROPERTIES));
  public static DeferredHolder<Block, RitualPedestalBlock> REINFORCED_RITUAL_PEDESTAL = BLOCKS.register("reinforced_ritual_pedestal", () -> new RitualPedestalBlock(BASE_REINFORCED_PROPERTIES));
  public static DeferredHolder<Block, GroveCrafterBlock> GROVE_CRAFTER = BLOCKS.register("grove_crafter", () -> new GroveCrafterBlock(BASE_WOODEN_PROPERTIES));
  public static DeferredHolder<Block, GrovePedestalBlock> GROVE_PEDESTAL = BLOCKS.register("grove_pedestal", () -> new GrovePedestalBlock(BASE_WOODEN_PROPERTIES));
  public static DeferredHolder<Block, GrovePedestalBlock> WILDWOOD_PEDESTAL = BLOCKS.register("wildwood_pedestal", () -> new GrovePedestalBlock(BASE_WOODEN_PROPERTIES));
  public static DeferredHolder<Block, GrovePedestalBlock> DISPLAY_PEDESTAL = BLOCKS.register("display_pedestal", () -> new GrovePedestalBlock(BASE_WOODEN_PROPERTIES));
  public static DeferredHolder<Block, WildRootsBlock> WILD_ROOTS = BLOCKS.register("wild_roots", () -> new WildRootsBlock(BASE_WOODEN_PROPERTIES.strength(0.2f)));
  public static DeferredHolder<Block, CreepingGroveMossBlock> CREEPING_GROVE_MOSS = BLOCKS.register("creeping_grove_moss", () -> new CreepingGroveMossBlock(BlockBehaviour.Properties.ofFullCopy(Blocks.MOSS_CARPET)));
  public static DeferredHolder<Block, HangingRootsBlock> HANGING_GROVE_MOSS = BLOCKS.register("hanging_grove_moss", () -> new HangingRootsBlock(BlockBehaviour.Properties.ofFullCopy(Blocks.HANGING_ROOTS)));
  public static DeferredHolder<Block, HugeMushroomBlock> BAFFLECAP_BLOCK = BLOCKS.register("bafflecap_block", () -> new HugeMushroomBlock(BlockBehaviour.Properties.ofFullCopy(Blocks.BROWN_MUSHROOM_BLOCK)));
  public static DeferredHolder<Block, GroveStoneBlock> PRIMAL_GROVE_STONE = BLOCKS.register("primal_grove_stone", () -> new GroveStoneBlock(BASE_PROPERTIES));
  public static DeferredHolder<Block, IncenseBurnerBlock> INCENSE_BURNER = BLOCKS.register("incense_burner", () -> new IncenseBurnerBlock(BASE_PROPERTIES));
  public static DeferredHolder<Block, MortarBlock> MORTAR = BLOCKS.register("mortar", () -> new MortarBlock(BASE_PROPERTIES));
  public static DeferredHolder<Block, PyreBlock> PYRE = BLOCKS.register("pyre", () -> new PyreBlock(BASE_WOODEN_PROPERTIES));
  public static DeferredHolder<Block, PyreBlock> REINFORCED_PYRE = BLOCKS.register("reinforced_pyre", () -> new PyreBlock(BASE_REINFORCED_PROPERTIES));
  public static DeferredHolder<Block, DecorativePyreBlock> DECORATIVE_PYRE = BLOCKS.register("decorative_pyre", () -> new DecorativePyreBlock(BASE_WOODEN_PROPERTIES.lightLevel((o) -> 15)));
  public static DeferredHolder<Block, UnendingBowlBlock> UNENDING_BOWL = BLOCKS.register("unending_bowl", () -> new UnendingBowlBlock(BASE_PROPERTIES));
  public static DeferredHolder<Block, MushroomBlock> BAFFLECAP = BLOCKS.register("bafflecap", () -> new MushroomBlock(ModFeatures.CONFIGURED_HUGE_BAFFLECAP_KEY, BlockBehaviour.Properties.ofFullCopy(Blocks.BROWN_MUSHROOM)));
  public static DeferredHolder<Block, ThreeStageCropBlock> WILDROOT_CROP = BLOCKS.register("wildroot_crop", () -> new ThreeStageCropBlock(ModItems.WILDROOT, CROP_PROPERTIES));
  public static DeferredHolder<Block, ElementalCropBlock> CLOUD_BERRY_CROP = BLOCKS.register("cloud_berry_crop", () -> new ElementalCropBlock(ModItems.CLOUD_BERRY, CROP_PROPERTIES));
  public static DeferredHolder<Block, WaterElementalCropBlock> DEWGONIA_CROP = BLOCKS.register("dewgonia_crop", () -> new WaterElementalCropBlock(ModItems.DEWGONIA, CROP_PROPERTIES));
  public static DeferredHolder<Block, ElementalCropBlock> INFERNO_BULB_CROP = BLOCKS.register("inferno_bulb_crop", () -> new ElementalCropBlock(ModItems.INFERNO_BULB, CROP_PROPERTIES));
  public static DeferredHolder<Block, ElementalCropBlock> STALICRIPE_CROP = BLOCKS.register("stalicripe_crop", () -> new ElementalCropBlock(ModItems.STALICRIPE, CROP_PROPERTIES));
  public static DeferredHolder<Block, BaseBlocks.SeededCropsBlock> MOONGLOW_CROP = BLOCKS.register("moonglow_crop", () -> new BaseBlocks.SeededCropsBlock(ModItems.MOONGLOW_SEEDS, CROP_PROPERTIES));
  public static DeferredHolder<Block, BaseBlocks.SeededCropsBlock> PERESKIA_CROP = BLOCKS.register("pereskia_crop", () -> new BaseBlocks.SeededCropsBlock(ModItems.PERESKIA_BULB, CROP_PROPERTIES));
  // TODO: Pottable pereskia?
  public static DeferredHolder<Block, ThreeStageCropBlock> SPIRITLEAF_CROP = BLOCKS.register("spiritleaf_crop", () -> new ThreeStageCropBlock(ModItems.SPIRITLEAF_SEEDS, CROP_PROPERTIES));
  public static DeferredHolder<Block, BaseBlocks.SeededCropsBlock> WILDEWHEET_CROP = BLOCKS.register("wildewheet_crop", () -> new BaseBlocks.SeededCropsBlock(ModItems.WILDEWHEET_SEEDS, CROP_PROPERTIES));
  public static DeferredHolder<Block, BaseBlocks.SeededCropsBlock> AUBERGINE_CROP = BLOCKS.register("aubergine_crop", () -> new BaseBlocks.SeededCropsBlock(ModItems.AUBERGINE_SEEDS, CROP_PROPERTIES));
  public static DeferredHolder<Block, BaseBlocks.WildCropBlock> WILD_AUBERGINE = BLOCKS.register("wild_aubergine", () -> new BaseBlocks.WildCropBlock(RootsTags.Blocks.SUPPORTS_WILD_AUBERGINE, CROP_PROPERTIES));
  public static DeferredHolder<Block, FlowerPotBlock> POTTED_BAFFLECAP = BLOCKS.register("potted_bafflecap", () -> new FlowerPotBlock(() -> (FlowerPotBlock) Blocks.FLOWER_POT, ModBlocks.BAFFLECAP, BlockBehaviour.Properties.ofFullCopy(Blocks.OAK_SAPLING)));
  public static DeferredHolder<Block, FlowerPotBlock> POTTED_STONEPETAL = BLOCKS.register("potted_stonepetal", () -> new FlowerPotBlock(() -> (FlowerPotBlock) Blocks.FLOWER_POT, ModBlocks.STONEPETAL, BlockBehaviour.Properties.ofFullCopy(Blocks.OAK_SAPLING)));
  public static DeferredHolder<Block, FlowerPotBlock> POTTED_WILDWOOD_SAPLING = BLOCKS.register("potted_wildwood_sapling", () -> new FlowerPotBlock(() -> (FlowerPotBlock) Blocks.FLOWER_POT, ModBlocks.WILDWOOD_SAPLING, BlockBehaviour.Properties.ofFullCopy(Blocks.OAK_SAPLING)));

  public static void register(IEventBus modEventBus) {
    BLOCKS.register(modEventBus);
  }
}
